### PR TITLE
fix: kolour nft owner address

### PR DESCRIPTION
**Pull request by sk-umiuma**
~~TODO: genesis kreation nft owner address~~

### CODE REVIEW

**Comment by sk-kitsune** [comment]
@sk-umiuma is this PR ready for review?

@sk-shishi  Please help to review the backend part (esp. SQL queries). Thanks!

**Comment by sk-umiuma** [comment]
No, there are still more thing to be refined. In the meantime, please review the others.

**Comment by sk-kitsune** [comment]
@sk-umiuma is this PR ready?

**Comment by sk-kitsune** [comment]
@sk-shishi  please help to review, thanks!

**Review by sk-yagi — APPROVED** [review]

**Comment by sk-shishi** [comment]
I trust you

**Pull request merged**
